phaserjs/phaser-ce

- typescript/phaser.d.ts
Phaser.d.ts fix for Phaser.Plugin.AStar.DISTANCE_MANHATTAN (was DISTANCE_MANHATTEN) to match https://github.com/photonstorm/phaser-plugins/blob/master/AStar/AStar.js
Oops, I missed the DISTANCE_MANHATTEN :)
Too bad this PR didn't quite make it to 2.7.3 (with the COST_ORTHAGONAL and COST_DIAGAONAL fix) but better late than never I guess.
> Fixed a typescript definition to match source.

- CHANGELOG.md
- src/particles/arcade/Emitter.js
Fixes #7. Also clarifies zero `quantity` in Emitter.start().
> Explode all particles by default

- CHANGELOG.md
- src/physics/arcade/TilemapCollision.js
- src/tilemap/Tilemap.js
- src/tilemap/TilemapLayer.js
- src/tilemap/TilemapParser.js
This PR changes **the public-facing API**.
It implements offsetting tilemap layer positions in a way that plays well with the camera and Arcade physics.
It includes support for the Tiled map `offsetx` and `offsety` layer properties.
> Implemented TilemapLayer offset

- CHANGELOG.md
- typescript/phaser.d.ts
- Fixed module name for phaser-ce
- Fixed AStar plugin definition to get grunt tsdocs work again, which currently breaks with an error
Fixes: #29
> Fix to get grunt tsdocs work again

- CHANGELOG.md
- src/physics/p2/Body.js
Description:
Allows the loaded polygon through `loadPolygon()` to be rescaled. If you plan on using different sized Sprites, you would probably want to use different sized bodies. The scale can't be changed later, but that wouldn't matter if the Sprite using this polygon has a constant scale. I've used this reworked method for a while and it has been working perfectly so far, even with negative numbers.
> Add loadPolygon() rescale functionality

- CHANGELOG.md
- src/physics/arcade/TilemapCollision.js
- src/tilemap/TilemapLayer.js
This PR changes **the public-facing API**.
I decided to squeeze this renaming in now to avoid backwards compatible changes with later Phaser CE versions, as I'm working on [something](https://github.com/hexus/phaser-ce/commits/tilemap-scaling "Camera and tilemap scaling!") that may not be finished in time for 2.7.4.
> Refactored layerOffsetX and layerOffsetY properties to tileOffset property

- typescript/phaser.comments.d.ts
- typescript/phaser.d.ts
This PR changes: TypeScript Defs
added missing method definition for Phaser.Group.GetAll()
> missing definition in phaser.d.ts

- src/gameobjects/Text.js
Instead a copy is kept
setStyle is currently a mutator method that keeps a reference to the passed in style parameter. If the user modifies this style later, then the Text will be effected. Likewise, setting default params on this style means it cannot be reused between texts without being altered
> update Text.setStyle to not mutate the passed style

- src/loader/Loader.js
closes #53
Resets the loaders state before calling the complete callbacks.
> Resetting loader state before complete callbacks.

- src/pixi/display/Sprite.js
Fixed crashes on very old devices
In some versions of javascript, drawImage will crash if the given coordinates are outside the size of the source.
> Fixed rendering on devices that use older versions of javascript

- src/core/Group.js
If a sprite is destroyed during another sprite's update function, the game will no longer crash.
> Fixed group updating if a sprite has been destroyed

- CHANGELOG.md
- src/core/Group.js
- src/gameobjects/Image.js
- src/particles/arcade/Emitter.js
- typescript/phaser.d.ts
- Added preUpdateLifeSpan for Image
- Added missing parameter particleArguments at typescript definition file
- Extended changelog markdown
Added call of preUpdateLifeSpan within Image as written within the documentation. Fixed also bunch of jshint issues and added missing typescript parameter for method makeParticles.
resolve #46
> Fixed jshint issues and image life span update

- CHANGELOG.md
- src/input/Input.js
Chrome version 55 or above introduces PointerEvents, and emits both touch and pointer events when a touch is performed.
This code simply skips initialisation of touch event handlers (touch.start()) if Pointer events are available.
Fixes #32
Moving forward, it might be better to rename src/input/MSPointer.js to a more generic name, seeing that PointerEvent possibly gaining acceptance across major browsers.
> Fix duplicate touch events in Android Chrome >= 55

- README.md
- src/polyfills.js
Object.assign was only recently added, so older devices don't support it. This checks if the Object.assign function exists, and if it doesn't, an alternative function is created.
> Fixed Object.assign for older devices that don't support it

- README.md
- typescript/phaser.d.ts
Fixed typescript definition files of `TilemapLayer#getRayCastTiles`, `TilemapLayer#getTiles`, `TilemapLayer#getTileX`, `TilemapLayer#getTileXY` and `TilemapLayer#getTileY`
Fixes #75
> Fixed typescript definitions for getTile

- README.md
- src/gameobjects/BitmapText.js
This PR changes: it’s a bug fix
> Reset glyph's cachedTint in BitmapText#updateText() (#58)

- src/core/Group.js
This PR changes: Documentation (related: #48)
> Mark `checkAlive` and `checkVisible` optional in Group#addAll()

- typescript/phaser.d.ts
This PR changes :  TypeScript Defs
As mentioned in post issue#45 , these two parameters (checkAlive:boolean, checkVisible:boolean) should be optional,, in case they're not provided when calling the method , they're implicitly set to falseanyway while calling Phaser.Group.setAll() method afterwards.
> Updated method definition for Phaser.Group.AddAll() - phaser.d.ts

- typescript/phaser.comments.d.ts
This PR changes : TypeScript Defs
As mentioned in post photonstorm/phaser-ce#45 , these two parameters (checkAlive:boolean, checkVisible:boolean) should be optional,, in case they're not provided when calling the method , they're implicitly set to falseanyway while calling Phaser.Group.setAll() method afterwards.
> Updated method definition for Phaser.Group.AddAll() - phaser.comments.d.ts

- typescript/phaser.d.ts
TypeScript Defs
Added centerX and centerY properties to Phaser.Graphics.
According to the API docs it should be exposed as public. prop.
> Added missing  properties to Phaser.Graphics - phaser.d.ts

- README.md
- src/input/Keyboard.js
This PR changes: a bug fix (#132)
> Don't read null events in Phaser.Keyboard#lastChar

- README.md
- src/sound/Sound.js
This PR is a bug fix for #157
Extended audiotag volume clamping to all browsers, according to the documentation audiotag volume must between 0 and 1 (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio)
> Fixes #157 Extended audiotag volume clamping to all browsers

- src/loader/Loader.js
Bug Fix: This will now account for query strings on the filename, which is common when using build systems to cache-bust the files.
> Improve extraction of file extension

- README.md
- src/core/Game.js
- src/particles/Particles.js
Fixes #160
Also deprecates Phaser.Particles#update since Phaser no longer uses it
> Don't update game.particles during game.updateLogic()

- README.md
- src/loader/LoaderParser.js
- typescript/phaser.d.ts
Adds missing `resolution` default value in
- bitmapFont()
- jsonBitmapFont()
- xmlBitmapFont()
Corrects Typescript definitions for same
Fixes #168
> Fix Phaser.LoaderParser BitmapFont methods

- README.md
- src/loader/Loader.js
This removes the upper limit of 12 from `maxParallelDownloads` in the `Loader` and addresses #170. The default remains at 4 while allowing the user to set the value to anything from `1` to `Infinity`.
> Allow setting maxParallelDownloads to higher values

- README.md
- typescript/phaser.comments.d.ts
- typescript/phaser.d.ts
Replaced 'any' with 'PhaserTextStyle' for style parameters in GameObjectFactory#text and GameObjectCreator#text. These now line up with the type used in the Text constructor.
This enables autocompleting of fields within a style object when using the .add and .make syntax.
> Add types for style parameters in Typescript definitions

- README.md
- src/gameobjects/Text.js
Phaser.Text can have it's alignment set as any arbitrary string, but was only compared against lowercase left/middle/right. string#toLowerCase() is now called on the alignment before comparison.
> Text now handles alignment being set in upper or mixed case.

- src/pixi/renderers/webgl/shaders/PixiFastShader.js
- src/pixi/renderers/webgl/shaders/PixiShader.js
- src/pixi/renderers/webgl/shaders/StripShader.js
- src/pixi/renderers/webgl/utils/WebGLSpriteBatch.js
This PR changes  Nothing, it's a bug fix
I was trying to enable  multitexture in modern GPU (Intel 530 and NVIDIA 950M) that has 16 texture units, but when try to compile the fragment shader occour error because the nested ifs. I suspect that there is a limit about nested ifs in GLSL and the if else if else if ... throws this error. I change to if  statement return , avoiding use the else if
> Removing nested ifs. GLSL has limits of nested ifs.

- README.md
- src/core/Group.js
The documentation implies that property is an optional parameter, however the getAll() function will only return an empty array if no property parameter is provided.
> Get all children of a group if no property parameter is provided

- .npmignore
Hi, @samme, @photonstorm.
I'm sending this PR as a proposal to make some adjustements to the Phaser CE package. It is not a big change (just only an additional file), but it changes the contents distributed through npm. I'd like to ask you to review this change carefully. I am able to update this PR, if requested.
The problem is that `phaser-ce` package is too big, much because it includes contents not relevant for a npm package. Right now, running `npm pack .` against the master branch will create a TAR+GZIP archive which sits at around 36MB of size, ~94MB uncompressed ─ Think of `npm pack` as a "dry-run mode" of `npm publish`.
My proposal is to remove, among other things:
*   The `resources` folder, which contains miscellaneous files;
*   The Grunt tasks, because it is unusual to keep …
> Reduce npm package size.

- README.md
- src/particles/arcade/Emitter.js
The problem is that setting `emmiter.setScale(-1, -1)` is doing nothing. because if expects different values. This is an attemps to fix that.
> Set x and y scale when the values are identical

- README.md
Changed to 2.7.7 in the meantime, which does.
Make sure you describe your PR in the [README Change Log](../README.md#change-log) section!
> Version 2.7.9 doesn't exist as a CDN

- src/time/Timer.js
If you try to destroy a looping timer, it will never actually get removed from the `game.time._timers` array because `expired` never gets set to `true`. Directly setting `expired = true` in `destroy` seems to fix this issue.
> Set timer to expired on destroy

- src/tilemap/Tilemap.js
Just a tiny fix in the warning message, where it would always show `null` instead of the invalid layer ID being passed to the method.
> Fix "Invalid layer ID" warning message.

- README.md
- src/sound/Sound.js
This PR changes:
When using Audio Tag and setting global volume and then using something like fadeTo sound volume on Audio Tag ignores global volume this fixes that. This problem is Audio Tag specific WebAudio works correctly without this fix.
You can notice this when after lowering global volume you turn on some fadeOut sound transition you can hear volume spike in beginning of this transition.
> Xesenix patch 1

- src/gameobjects/Text.js
text style `strokeThickness` breaks text if entered as a string, without error or indication.
Solution: Cast strokeThickness value to number to ensure a number value or NaN
Refs #239
> fix for #239

- CHANGELOG.md
- typescript/phaser.d.ts
Make sure you describe your PR in the [README Change Log](https://github.com/photonstorm/phaser-ce/blob/master/README.md#change-log) section!
I updated the phaser.d.ts file. The multiTexture property was mistyped multiTextue. I'm pretty n00b when it comes to typings, so if I changed it at the wrong place or something, please let me know and I will correct it.
> Typings typo fixed

- README.md
- src/core/Camera.js
Camera._shake.x and y weren't being set to 0 on camera reset, causing
the camera to get stuck in the wrong position.
> Fix camera shake #246

- src/input/Input.js
Make sure you describe your PR in the [README Change Log](https://github.com/photonstorm/phaser-ce/blob/master/README.md#change-log) section!
Fixed hitTest function not taking device resolution into account when an image resolution is added dynamically using @{n}x notation on a asset.
> Fixed hittest not taking device resolution into account

- README.md
- typescript/phaser.comments.d.ts
- typescript/phaser.d.ts
Make sure you describe your PR in the [README Change Log](https://github.com/photonstorm/phaser-ce/blob/master/README.md#change-log) section!
Playing around with move callbacks, I noticed the TypeScript definitions differed a little from the actual implementation:
- Phaser.Input.moveCallbacks: certainly not a single closure returning a void-array, but an array of objects containing both a callback and a context to execute the callback in. Also the `fromClick` parameter was missing from the callback signature.
- Phaser.Input.addMoveCallback: added the full callback signature for better type-checking. Changed the return type form `number` to `void`, since it doesn't actually return anything. Made the …
> Fix TypeScript definitions for move callbacks

- typescript/phaser.d.ts
Make sure you describe your PR in the [README Change Log](https://github.com/photonstorm/phaser-ce/blob/master/README.md#change-log) section!
I've noticed **scaleMode** parameter is missing from typescript **IGameConfig** definition. The parameter is available into phaser-ce documentation.
Tell me if i did something wrong (It's been a while i did not make a pull request from github). ;)
> Typescript : missing scaleMode parameter for IGameConfig

- README.md
- src/input/InputHandler.js
- [v] This PR includes a description of these changes in [README.md: Change Log: Unreleased](https://github.com/photonstorm/phaser-ce/blob/master/README.md#unreleased).
alphaThreshold was documented as a boolean despite being an integer.
> Correct documentation for InputHandler#enableDrag

- README.md
- src/gameobjects/Video.js
- src/input/Input.js
- src/input/MSPointer.js
- src/input/Touch.js
- src/sound/SoundManager.js
* is a bug fix (closes #37)
Moved addTouchLockCallback and removeTouchLockCallback from Phaser.Touch to Phaser.Input so they can also be used for Phaser.MSPointer (Pointer Events). Also added touchLock callback to chrome versions > 55 due to audio not playing on mobile when in an cross-origin iframe. MSPointer now also handles touchlocks
> Fixed for unlocking audio with Pointer Events

- src/animation/Animation.js
* is a bug fix
-----------------------
There was a problem with Animations where there would be lagging or sped up animations due to lower framerate than what Phaser expects.
The first frame a delay is detected, it compensates perfectly, but on the succeeding frames, it compensates too much and disynchronises animations.
This is our fix for the Animation problem we encountered and we wanted to share this with CE.
We hope it will help some people have an easier time with anims on slower devices such as small tablets or old phones.
-----------------------
> Animation synchronization problem and solution

- README.md
- src/pixi/display/Sprite.js
This PR:
* is a bug fix
* Fix check of destroyBase in PIXI.Sprite.setTexture to not destroy old texture if set to false
> Fix PIXI.Sprite.setTexture destroying old texture when destroyBase is false

- README.md
- src/input/DeviceButton.js
- src/input/Pointer.js
This PR
* changes documentation (sortof)
* adds two new internal functions (in Phaser.Pointer and Phaser.DeviceButton)
* changes internal functions in Phaser.Pointer
* makes this PR obsolete #318
* is a bug fix (closes #250, closes #293)
✓ ~~Please include a summary in [README.md: Change Log: Unreleased](https://github.com/photonstorm/phaser-ce/blob/master/README.md#unreleased) and thank yourself.~~
You can test with this build: https://gs.breitzeit.de/phaser/builds/phaser-fix_mspointer_yay_p340.js
* Added new (internal) helper function `Phaser.DeviceButton#startStop`
_Mainly to make the already long upDown function shorter, it's not used anywhere else but with \_this\_ coding preference it would add so many lines to the upDown function..._
* Added new …
> Fix mspointer (mostly), yay! 🎉

- typescript/phaser.d.ts
The phaser.d.ts definition of the game.physics.Arcade class is missing 'isPaused': boolean which is implemented in src/physics/arcade/World.js line 72
> add Arcade isPaused boolean to ts definition

- typescript/phaser.d.ts
The d.ts file is missing the blendMode on module Particles > Arcade > class Emitter; It can be found in particles/arcade/Emitter.js, line 161
> add Arcade > Emitter blendMode to ts definition

- src/tween/TweenData.js
this.interpolationFunction call in generateData function in TweenData.js didn't apply context
> this.interpolationFunction call bug fix

- typescript/phaser.d.ts
Bug fix in phaser.d.ts Particles.Arcade.Emitter.blendMode - type should be PIXI.blendModes, not PIXI.blendMode
> phaser.d.ts PIXI.blendMode bugfix

- README.md
- src/utils/Color.js
I have A function for interpolating in HSV ([source](http://www.alanzucconi.com/2016/01/06/colour-interpolation/2/)) in one of my codepens, figured why not add it as a feature...
* added color space option (RGB or HSV) in [Phaser.Color.interpolateColor](https://photonstorm.github.io/phaser-ce/Phaser.Color.html#_interpolateColor). RGB or HSV. 
The default is RGB space. A seperate function to do this is also possible, but I figured this might be most suitable (let user choose color space).
Hue shift is clockwise  when the angle is exactly 180 degrees. for example:
red (0xff0000) to cyan (0x00ffff) will take the [clockwise](https://user-images.githubusercontent.com/30023855/30649786-7e091f10-9e21-11e7-8eea-4c1439ee5879.png) …
> Phaser.Color.interpolateColor HSV option

- README.md
- src/physics/p2/World.js
- src/tilemap/TilemapParser.js
This PR
Hey, everyone. First off, thanks to everyone who's maintaining and contributing to this repo. It's been really cool to see all of the activity, merged PRs, and closed issues just in the few days that I've been working on this PR.
I'm very new to Phaser, but not new to JS and Tiled. I wrote a Ruby adapter for Tiled's `.tmx` format recently, so I was excited to see that Phaser has support for the format baked in. I noticed a few things that seem to be useful/common workflows in Tiled that weren't yet supported in Phaser. After combing through a number of blog posts, forums messages, and GitHub issues circa 2014-2017, I thought this patch might be useful to other people, as well. This PR attempts to address a couple of the …
> Improved tiled support

- README.md
- src/tilemap/Tilemap.js
This PR
* is a bug fix
Currently, setting `visible = true` in an object layer in Tiled doesn't work when calling `createFromObjects`. After digging into why, I realized that `Phaser.Tilemap#createFromObjects` sets `sprite.visible` before setting `sprite.exists`, but `sprite.exists` has a custom setter that overrides the `visible` property (see https://github.com/photonstorm/phaser/blob/v2.4.4/src/gameobjects/components/Core.js#L277). This just reorders the assignments so that visibility is set afterwards. Appears to fix the issue.
> Prevent Phaser.Tilemap#createFromObjects from overriding sprite visibility as set in Tiled

- README.md
- src/tilemap/Tilemap.js
This PR is a bug fix.
`Phaser.Tilemap#setTileIndexCallback`'s documentation indicates that callbacks can be removed by passing in null as the callback argument (see https://github.com/photonstorm/phaser/blob/v2.4.4/src/tilemap/Tilemap.js#L751). This removes the callback object as expected.
This was originally opened as https://github.com/photonstorm/phaser-ce/pull/376, but this cleans up the commit log a bit. Thanks!
> Removing callback on a tile to null now works as expected

- README.md
- src/gameobjects/BitmapText.js
This PR 
* is a bug fix 
Fixed issue that ignored a new line if the last character being evaluated on the scanLine function of a BitmapText exceeded the maxWidth of said text. This bug would prevent the last part of a text to be shown, as the scanLine function would think the text has already ended, even if it was by itself cutting out the last part.
> Fixed issue that prevented BitmapText's text to be shown completely.

- README.md
- src/core/StateManager.js
This PR 
This simply updates the grammar in the error message when the state manager is provided an object that isn't a valid State.
> Fix grammar in invalid state message

- README.md
- src/tilemap/Tilemap.js
This PR
Add adjustSize parameter to Phaser.Tilemap#createFromObjects. Setting this to false will disable copying object width and height to the sprite
> Add adjustSize parameter to Phaser.Tilemap#createFromObjects

- README.md
- typescript/p2.d.ts
This PR:
The suggested typings comes from the official p2 typings. (from DefinitelyTyped)
I copy/paste the whole typings because they are not compatible with the phaser version.
> Update p2.js typings

- README.md
- src/loader/Loader.js
This PR:
* is a bug fix
Avoid raising this following error if state has been destroyed during async loading:
```
Uncaught TypeError: Cannot read property 'loadComplete' of null
at Phaser.Loader.finishedLoading
at Phaser.Loader.processLoadQueue
at Phaser.Loader.asyncComplete
at Phaser.Loader.fileComplete
at Image.file.data.onload
```
> Fix async load complete when state is destroyed

- CHANGELOG.md
- typescript/phaser.comments.d.ts
- typescript/phaser.d.ts
added typescript definitions for Phaser.Sprite.outOfCameraBoundsKill boolean
> added typescript definitions for sprite.outOfCameraBoundsKill boolean

- src/gameobjects/Rope.js
Removed mistyped sequence of points property setup from constructor
> [bug] Rope.js fixed sequentional setup of optional 'points' argument

- src/core/Game.js
- src/input/Input.js
This PR
When game is paused, input events from gamepad controllers are not handled.
This prevents any user interaction trough gamepad if game gets paused when opening game menus and basically blocks the game since user can not exit the menu or choose any option if there are no other input methods available (like keyboard, mouse or touch events).
It ruins the players' experience or forces developer to not use gamepads or drastically change game code in order to do so.
This PR enables gamepad controllers to be used while game is paused and solves this issue.
> Enabling Gamepad input while game is paused

- README.md
- src/gameobjects/components/Smoothed.js
This PR
* is a bug fix
I just came across an issue while using the WebGL renderer.
When updating the 'smoothed' property on a Sprite it did not flag the base texture as dirty. This meant that if you loaded the image as true and then flipped it to false later on it would remain smoothed. WebGL wasn't updating the texture's TEXTURE_MIN_FILTER. 
This now flags the texture as dirty when that property is updated.
> Bug fix for changing smoothing property in WebGL

- src/gameobjects/BitmapText.js
This PR
* is a bug fix
After seeing the forum post in the other PR: https://github.com/photonstorm/phaser-ce/pull/432
I saw that BitmapText manually sets the scaleMode which is why it wasn't working for that user. I've added the dirty call to the part of BitmapText that changes it so that it will fix the problem for that user too.
> Added texture dirty call to BitmapText for WebGL

- README.md
- typescript/phaser.d.ts
Fixed incorrect TypeScript defintion: Input.pointer to Input.pointers
> Fixed incorrect TypeScript defintion: Input.pointer to Input.pointers

- src/sound/Sound.js
- typescript/phaser.d.ts
This PR
This property addition will allow developers to flag a sound for deletion after it is played once.  This is a simple method for avoiding creating new `_sounds` entries for sounds that are intended to just be played once and done.
> Added a playOnce boolean in order to mark the sound for deletion after the initial play.

- README.md
- src/physics/arcade/World.js
This PR is a bug fix (closes #451)
The basis oriented along the direction of impact and the tangential speed is not converted properly during calculations. This change makes sure the same basis is used when converting back and forth.
> Fix separate circle physics

- README.md
- typescript/phaser.d.ts
This PR is a bug fix (closes #460 )
It changes TypeScript definition for bitmapText in GameObjectCreator
> Fixed TS definition for bitmapText in GameObjectCreator (closes #460)

- src/input/Mouse.js
Fix the issue of disabled input handler receiving pointerOutHandler when mouse goes out of canvas #454 
**Changes:**
Trigger ```Phaser.InputHandler#_pointerOutHandler``` only when enabled set to true.
*I don't confirm if any other solution better than this.*
> Fix mouse issue onInputOut signal

- README.md
- src/core/Game.js
Fixes a spelling error in the API documentation that appears here: 
https://photonstorm.github.io/phaser-ce/Phaser.Game.html#Game
> Fix spelling error in API documentation

- src/sound/Sound.js
This PR is a bug fix for issue #323 
I have modified Phaser.Sound#resume:
1. setting Phaser.Sound#_sound.loop to true only when ```currentMarker === ''```
2. Phaser.Sound#_sound.start filled with duration as parameter if ```currentMarker === ''```
Here if the modified version:
https://codepen.io/squaresun/pen/GQjLYo
I have tested on Safari (Mac OS and iOS) and Desktop Chrome but I don't confirm if this PR is safe enough.
> Fix audiosprite looping issue after paused

- src/sound/Sound.js
* is a bug fix 
Fixed Sounds did not loop when using Audio Object.
> Fixed sounds not looping when using audio.

- src/utils/Debug.js
This PR is a bug fix (closes #471)
> Displaying sprite.name in Debug.spriteInfo, as the documentation specifies

- README.md
- typescript/p2.d.ts
- typescript/pixi.comments.d.ts
- typescript/pixi.d.ts
Corrected 2 TypeScript definitions of p2:
* `frictionStiffness` in `ContactMaterial`
* constructor of `Convex`
> Fix p2.d.ts

- CHANGELOG.md
- README.md
- src/geom/Ellipse.js
Ellipse random points are being restricted to a smaller central area of the ellipse with a large padding between the points and the ellipse circumference.
This PR
* is a bug fix
Phaser.Ellipse.random() returned a point from within a smaller Ellipse than what was defined due to the width & height being divided by 2. Removed the division from both lines.
See screenshots attached to issue #522
> Ellipse random() area calculation for points fix

- src/core/State.js
This PR 
There appears to be a typo in State.js as mentioned by Issue #521 . This PR corrects "stage" to "state".
> Corrected doc typo re: state property from Issue #521

- README.md
- src/gameobjects/Text.js
This PR changes the public-facing API
Changes added to customize the character string that is used to calculate the text width and height. 
This was needed because the character sizing was calculated incorrectly and characters were being cut off when using localized font. (example: Thai "บิ๊กวิน")
> Customize character string used to calculate text width and height

- src/physics/Physics.js
This PR is a bug fix
Some other places may be related like the 2 following:
https://github.com/photonstorm/phaser-ce/blob/b213d6b60b2ceb401d00d8890e4d572af113702b/src/utils/Debug.js#L1053
https://github.com/photonstorm/phaser-ce/blob/b213d6b60b2ceb401d00d8890e4d572af113702b/src/utils/Debug.js#L1083
I don't have the Box2D plugin but I can't imagine 3 classes respectively named `BOX2D`, `Box2D`, `box2d` :smirk:
> Fix wrong spelling of Box2D plugin

- README.md
- src/core/Game.js
This PR changes documentation.
It turns out the documented `canvasId` property for `GameConfig` doesn't actually set an id attribute on the canvas. [Phaser is looking for a property named `canvasID` instead.](https://github.com/photonstorm/phaser-ce/blob/master/src/core/Game.js#L856)
This PR changes `canvasId` to `canvasID` in the docs for `GameConfig` to account for this. 
(You'll notice this PR doesn't include any changes to `docs/` - I figure those are generated on release and did not touch the grunt commands that make them. If you'd like me to also rebuild those docs as part of this PR, I certainly can!)
> Change unused GameConfig property canvasId to canvasID

- README.md
- typescript/phaser.comments.d.ts
- typescript/phaser.d.ts
This PR changes TypeScript definitions.
Fixed incorrectly modified TS definition for bitmapText (#461).
> Fixed TS definition for bitmapText in GameObjectFactory

- src/loader/LoaderParser.js
This PR
* is a bug fix (closes #562)
fullfill the function of LoaderParser.dds to initialize ddsHeader.glExtensionFormat
> fix: dds compression rendering support

- README.md
- typescript/phaser.d.ts
This PR
Fixed TS definition for clear in RenderTexture.
> Fixed TS definition for clear in RenderTexture

- README.md
- src/core/Game.js
This PR
* is a bug fix (closes #572)
Game now checks SoundManager's `muteOnPause` property whenever the game's `paused` property is set so one can control whether sounds play when the game is paused. Previously, the property was only used when the game focus was lost in the DOM.
CodePen example of changes using generated build: https://codepen.io/giniwren/pen/ajqMGX
> Updates Game to check SoundManager muteOnPaused when Game's paused property is set

- README.md
- src/gameobjects/BitmapData.js
Previously sending 0 would equate to a 'falsey' value and force defaults to be used instead, making it impossible to set a shadow with 0 blur or 0 xpos/ypos.
* is a bug fix
>  Fixed BitmapData.shadow ignoring 0 blur or 0 offset

- README.md
- src/loader/LoaderParser.js
Fixed issue causing BitmapFont to fail loading if a kerning value for a character that doesn't exist in the font is defined in the xml/json.
This PR
* is a bug fix
Simply adds an existence check before attempting to access the character data for a character that may or may not exist.
> Fix for BitmapFont loading issue when kerning is defined for a non-existing character

- README.md
- src/gameobjects/BitmapText.js
Back-ported BitmapText#letterSpacing property from Phaser 3 (https://github.com/photonstorm/phaser/pull/3480) (thanks @wtravO)
This PR
Adds a letterSpacing property to BitmapText to allow developer to add or remove spacing between characters.
> Add letterSpacing property to BitmapText

- README.md
- src/core/Camera.js
This PR
These are read-only properties representing the coordinates of the center of the viewport.
They're convenient for positioning Game Objects.
> Add Camera#centerX, Camera#centerY (Thanks @samme)

- README.md
- src/gameobjects/Creature.js
This PR
* is a bug fix
Simply uses the clone parameter of Phaser.Cache.getJSON to prevent the Creature runtime modifying the JSON object you give it from the Phaser.Cache making subsequent uses of that JSON not behave in various ways, depending on how you use the runtime (when having multiple Creature objects of the same character for example)
> Creature json safety fix

- src/gameobjects/Video.js
`HTMLMediaElement.mozSrcObject` has been removed with Firefox 58 and `URL.createObjectURL()` no longer accepts a stream as argument with Firefox 62
References:
* https://www.fxsitecompat.com/en-CA/docs/2017/htmlmediaelement-mozsrcobject-has-been-removed/
* https://www.fxsitecompat.com/en-CA/docs/2018/url-createobjecturl-no-longer-accepts-mediastream-as-argument/
> Video GameObject doesn't work on Firefox 62

- src/gameobjects/components/Smoothed.js
only mark texture as dirty when scaleMode differs from previous value
* is a bug fix 
Commit 7ea0dd2 a fix for #432 but marks texture always as dirty. Even if the smoothed value doesn't change at all. This fix now checks if the previous value actually differs to current. If it does, it marks the texture as dirty. This fixes some performance regressions for our framework that the commit introduced.
> Bugfix: Texture smoothing

- src/input/SinglePad.js
* is a bug fix 
When Gamepad got unplugged it sometimes got an buttons of undefined Error. In January we fixed the timestamp issue... but that hasn't solved it completely. I now ran the game with this proposed change for quite a while and no Error on unplug happened so far.
> Gamepad Unplug Error

- CHANGELOG.md
- src/core/Game.js
- src/gameobjects/components/LoadTexture.js
- src/gameobjects/components/Smoothed.js
- src/pixi/renderers/webgl/WebGLRenderer.js
- src/pixi/renderers/webgl/utils/WebGLFastSpriteBatch.js
- src/pixi/renderers/webgl/utils/WebGLSpriteBatch.js
This PR is a is a bug fix (closes #356)
- Fix for webGL making excessive gl calls, which was negatively impacting the frame-rate of low-end machines and mobile devices. (broken since original fork of phaser 2)
- Fix for smoothed setting on textures not being respected.
- Fix for updateTexture happening on textures that hadn't loaded their source yet.
- Fix for flickering issue on some android devices.
- Fix eslint errors.
> Fix for webGL performance on mobile devices and other issues

- src/core/Game.js
- src/pixi/renderers/webgl/WebGLRenderer.js
- typescript/phaser.d.ts
This PR
As the changelog doesn't seem to have an "unreleased" section, I didn't add to this. This is my first pull request to this project, so I suspect it may need some massaging / discussion; I was going to file an issue but decided it is probably best to try to make an effort to fix the problem instead of complain.
**Describe the changes below:**
This adds support for `powerPreference` hinting to the PIXI WebGLRenderer's context options, per the spec at https://www.khronos.org/registry/webgl/specs/latest/1.0/. In situations where a high-performance GPU is available (e.g. laptops with discrete GPUs) this offers the ability to hint to the browser that you would like to use one GPU or the other. Note that this may cause greater power consumption.
Per the …
> Add powerPreference hint to PIXI WebGLRenderer context options

- CHANGELOG.md
- src/pixi/renderers/webgl/utils/WebGLSpriteBatch.js
* is a bug fix (closes #644 )
simply reverted the breaking changes at  src/pixi/renderers/webgl/utils/WebGLSpriteBatch.js
> Reverting bugs introduced by PR #641 mentioned at issue #644 

- src/gameobjects/Video.js
- typescript/phaser.d.ts
Some storage services (i.e. S3) won't send CORS headers if the CORS attribute is not included in the request. The browser will refuse to load the video (createVideoFromURL) from S3.
https://docs.aws.amazon.com/AmazonS3/latest/dev/cors-troubleshooting.html (2.a)
"If the header is missing, Amazon S3 doesn't treat the request as a cross-origin request, and doesn't send CORS response headers in the response." 
More info:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-crosso …
> crossorigin attribute on video

- src/gameobjects/Video.js
- typescript/phaser.d.ts
This patch allows to pass constraint arguments to getUserMedia() via startMediaStream():
```
video.startMediaStream({
sampleSize: 8,
echoCancellation: true
}, null, null, {
facingMode: { ideal: 'user' },
width: 640,
height: 480
});
```
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints
> getUserMedia constraints

- src/tilemap/Tilemap.js
This PR
Adaptation of:
https://github.com/photonstorm/phaser/commit/fea65988f41e3b66461a4ee8698af9457dac6286
Tiled objects have properties as an array of objects like:
{ name: ..., type: ..., value: ...}
Update the parser to load these using the name/value properties instead
of just treating it as an array and loading properties named '0', '1',
etc.
sprite.setData does not exist in PhaserCE. therefore the property is set directly on the sprite.
> Respect tiled properties as an array

- src/geom/Point.js
fix Phaser.Point.multiplyAdd: so now it sums points and multiplies result. Earlier it multiplied only second point.
> fix Phaser.Point.multiplyAdd

- src/gameobjects/Rope.js
fix bug in Phaser.Rope: now if visibility is false, it won't render
> fix bug in Phaser.Rope

- src/loader/Loader.js
This PR is a bug fix (closes #742)
The game.load reference in the videoLoadEvent callback gets nulled when the game is destroyed. This uses the local reference for fileComplete instead.
> fix fileComplete reference error in Loader.loadVideoTag
