phaserjs/phaser-ce

typescript/phaser.comments.d.ts

Update phaser.comments.d.ts declared module name to match the package

---

CHANGELOG.md
src/math/Math.js

* The public-facing API (addition)

Add Phaser.Math.hypot()

---

CHANGELOG.md
src/physics/arcade/Body.js

Update Arcade Body bounds during reset

---

src/gameobjects/BitmapData.js

Drastically improves performance for updating a small portion of a large bitmap.
From: http://www.html5gamedevs.com/topic/27809-only-update-portion-of-bitmapdata/
Credit to: Fatalist
I don't have much experience adding anything to Phaser, hopefully someone can help me get this merged in properly.

Added function copyBitmapData

---

CHANGELOG.md
src/gameobjects/BitmapData.js

Updated comments, changed scope and added it to the changelog.

Updates for copyBitmapData

---

CHANGELOG.md
bower.json

Update bower name

---

CHANGELOG.md
src/physics/arcade/Body.js

Reset stored overlap values

---

src/gameobjects/Video.js

Updating the comments to keep it consistent with the changes from this issue: https://github.com/photonstorm/phaser/issues/2433

Comments Update

---

src/animation/AnimationManager.js

Clarify AnimationManager#updateIfVisible

---

CHANGELOG.md
src/core/Camera.js

Description:
I've previously described this problem [here](https://github.com/photonstorm/phaser/issues/2949).

Fix Camera glitching when its bounds are too small

---

src/physics/p2/Body.js

Add loadPolygon() parameter description

---

src/math/Math.js

Currently these functions are broken (well they cant get the edges) due to a bad conditional check. Thats my fault guys, sorry I committed that awhile back. You can do a quick test by copy+pasting into browser console and running some tests.
``` javascript
between = function (min, max) {
if (min === undefined) { min = 0; }
if (max === undefined) { max = 1; }
if (min === max)
{
return min;
}
if (min > max)
{
var temp = min;
min = max;
max = temp;
}
min = Math.ceil(min);
max = Math.floor(max);
return Math.floor(Math.random() * (max - min + 1)) + min;
}
console.log(between(0,1)); //its random so just let it run a couple of times
console.log(between(0,1)); console.log(between(0,1)); console.log(between(0,1)); …
```

Fix between and random

---

src/particles/arcade/Emitter.js

Update Emitter.js - allow custom arguments when creating "this.particleClass"

---

src/plugins/weapon/WeaponPlugin.js

https://github.com/photonstorm/phaser-ce/issues/66

fix local rotation tracking

---

src/sound/Sound.js

When you try to stop and disconnect an AudioBufferSouceNode at the same time generate a memory leak.

Fixes memory leak on webaudio resolve #64

---

CHANGELOG.md
README.md
typescript/phaser.d.ts

- Added some missing functions and changes within typescript definition added/changed with next release
- Updated changelist at changelog and readme
Fixes #69

- Updated changelist at changelog and readme

---

README.md
src/gameobjects/GameObjectFactory.js
src/plugins/weapon/WeaponPlugin.js

This PR changes: The public-facing API

Add `bulletClass` argument to game.add.weapon()

---

README.md
src/loader/Cache.js

Changes Cache#destroy()
Adds Cache#destroyItem()
Fixes #68

Destroy wrapped objects when clearing cache

---

src/core/Group.js
src/gameobjects/GameObjectFactory.js
src/particles/arcade/Emitter.js
src/plugins/weapon/WeaponPlugin.js

This PR changes: Documentation
- Emitter#particleClass
- GameObjectFactory#weapon()
- Group#classType
- Weapon#bulletClass
Also whitespace :/
Addresses #101

Change Group#classType and others' type to function

---

src/physics/arcade/Body.js
src/physics/arcade/World.js

Update Arcade Physics docs

---

README.md
src/loader/Cache.js
src/polyfills.js
typescript/phaser.d.ts

- Fixed typescript definitions
- Fixed jshint issues
Fixes #101

Fixed typescript definitions and jshint issues

---

README.md
src/sound/Sound.js

This PR changes: it’s a bug fix (#78)
Thanks @trpzn, @vpmedia

Fix audio skipping when restarting playback (#78)

---

README.md
src/physics/arcade/Body.js

This PR changes: The public API
- adds Phaser.Physics.Arcade.Body#updateCenter()
- changes Phaser.Physics.Arcade.Body#preUpdate()
Fixes #122

Recalculate center after updateMotion()

---

README.md
src/particles/arcade/Emitter.js

This PR changes: Documentation

Clarify Emitter#start

---

README.md
src/physics/arcade/World.js

This PR changes: no API differences
Fixes #131

Use Phaser.Math in velocityFromAngle

---

README.md
src/utils/Device.js

Changes Phaser.Device._checkCanvasFeatures
Fixes #130

Loosen check for device.canUseMultiply

---

README.md
src/gameobjects/BitmapData.js
typescript/phaser.d.ts

Add callback to BitmapData#generateTexture

---

README.md
src/loader/Cache.js

Load DEFAULT and MISSING textures asynchronously

---

README.md
src/animation/Frame.js
src/loader/Cache.js

Helps detect #136, #138, and similar.

Add warnings in Phaser.Cache#getImage, Phaser.Frame

---

src/loader/Cache.js

Make sure onload is always called in Cache#addDefaultImage, addMissingImage

---

src/gameobjects/BitmapData.js

Ensure callback is always called in BitmapData#generateTexture

---

README.md
src/gameobjects/BitmapData.js
src/loader/Loader.js
typescript/phaser.d.ts

Add Phaser.Loader#imageFromBitmapData

---

README.md
src/particles/arcade/Emitter.js
src/physics/arcade/Body.js

Remove Physics.Arcade.Body.html#checkCollision.any

---

README.md
src/loader/Loader.js

Fix loading compressed textures

---

README.md
src/pixi/renderers/webgl/utils/WebGLGraphics.js

Fixed runtime exception in WebGLGraphics.renderGraphics

---

README.md

Fix the browserify/commonjs doc

---

build/creature.js
src/gameobjects/Creature.js

creature upgrades for pixel scaling and anchor point setting

creature upgrades for pixel scaling and anchor point setting

---

README.md
src/animation/creature/CreatureMeshBone.js
src/gameobjects/Creature.js

creature anchor point, pixel scaling implementation from creature
runtimes

Creature anchor points pixel scaling

---

src/input/InputHandler.js

This PR is a bug fix (closes #297).

FIXED: bug when dragging sprites that are fixed to camera

---

README.md
src/gameobjects/Button.js
src/input/Input.js
src/input/Pointer.js

Fixed #392: Phaser.PointerMode.TOUCH -> Phaser.PointerMode.CONTACT

---

typescript/p2.d.ts

This PR changes TypeScript definitions.

fix p2 definition

---

src/gameobjects/BitmapData.js

This PR
* is a bug fix (I believe)

BitmapData#copy: always return BitmapData object

---

README.md
src/loader/LoaderParser.js

This PR is a bug fix.
Fixed a BitmapFont frame error when using trim frame in atlas.

Fixed a BitmapFont frame error when using trim frame in atlas.

---

src/input/SinglePad.js

https://github.com/photonstorm/phaser-ce/issues/610
* is a bug fix ( closes #610 )

Gampad Unplug Error "timestamp"

---

src/gameobjects/Creature.js

Alpha for the whole Creature Object does work. But for single regions it didn't.
This commit fixes the alpha region bug. Animating alpha for regions in creature now also displays correctly in phaser. We are using this for a framework of our own which is based on phaser ce. So this is tested and works.

Creature Module Region Alpha Fix

---

CHANGELOG.md
src/core/ScaleManager.js

#626 tell requestFullscreen to hide the navigation UI
